---
kind: pipeline
type: docker
name: Mega-Linter
workspace:
  path: /drone/src
steps:
  - name: Lint
    image: 'oxsecurity/megalinter:v6'
    environment:
      DEFAULT_WORKSPACE: /drone/src

---
kind: pipeline
type: docker
name: default
steps:
  - name: Test
    image: buildpack-deps:latest
    commands:
      - ./scripts/test.sh
    environment:
      STOW_TARGET: /opt/stow
  - name: Coverage
    image: alpine:latest
    failure: ignore
    commands:
      # https://docs.codecov.io/docs/about-the-codecov-bash-uploader
      # https://docs.codecov.com/docs/codecov-uploader#integrity-checking-the-uploader
      - apk add curl gnupg coreutils
      - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
      - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
      - sha256sum -c codecov.SHA256SUM
      - chmod +x codecov
      - ./codecov -t ${CODECOV_TOKEN}
    environment:
      CODECOV_TOKEN:
        from_secret: 'codecov-upload-token'

---
kind: secret
name: codecov-upload-token
data: 'z1esy/MHWVnCY8epSwh3UAn+fviMhfUUKyqf2tKeMboA+9M5ZGfMy4BH+KJD/rzRW/QSFQ1n0GnyiL3lXROaOQ=='
