version: 2.1

orbs:
  codecov: codecov/codecov@5.2.0

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    docker:
      - image: homebrew/brew:latest
        # checkov:skip=CKV_CIRCLECIPIPELINES_1:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Test
          command: |
            brew bundle install
            ./scripts/test.sh
          environment:
            HOMEBREW_BUNDLE_NO_LOCK: 1
      - codecov/upload

workflows:
  CI:
    jobs:
      - MegaLinter
      - test
