name: CI
on:
  - push
env:
  GUIX_PACK_CACHE: /opt/guix-pack.tar.gz
  GUIX_PACK_ROOT: /opt/guix
  STOW_TARGET: /opt/stow
jobs:
  Mega-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Mega-Linter
      - name: Mega-Linter
        id: ml
        # You can override Mega-Linter flavor used to have faster performances
        # More info at https://megalinter.github.io/flavors/
        uses: megalinter/megalinter@v5
        env:
          # All available variables are described in documentation
          # https://megalinter.github.io/configuration/
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Mega-Linter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Mega-Linter reports
          path: |
            report
            mega-linter.log

  guix-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Guix pack
        id: guix_pack_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GUIX_PACK_CACHE }}
          key: guix-pack-cache-${{ hashFiles('manifest.scm') }}

      - name: Guix cache
        if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/guix
          key: guix-cache-${{ hashFiles('**/manifest.scm') }}
          restore-keys: |
            guix-cache-

      - name: Install Guix
        if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
        uses: PromyLOPh/guix-install-action@v1

      - name: Guix Pack
        if: ${{ ! steps.guix_pack_cache.outputs.cache-hit }}
        run: |
          guix pack --format=tarball --relocatable --relocatable --symlink=/bin=bin --root=/tmp/guix-pack.tar.gz --manifest=manifest.scm
          cp /tmp/guix-pack.tar.gz "${{ env.GUIX_PACK_CACHE }}"
          # /tmp/guix-pack.tar.gz is a symlink which points to Guix store.  Copy it.

  test:
    needs:
      - guix-pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Guix pack
        id: guix_pack_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GUIX_PACK_CACHE }}
          key: guix-pack-cache-${{ hashFiles('manifest.scm') }}

      - name: Unpack Guix Pack
        run: |
          mkdir -p "${{ env.GUIX_PACK_ROOT }}"
          tar x -z -f "${{ env.GUIX_PACK_CACHE }}" -C "${{ env.GUIX_PACK_ROOT }}" -v

      - name: Test
        run: |
          ./scripts/test.sh

      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          verbose: true
